config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :notes
  get 'test' => 'pages#testpage'
  get 'preview' => 'pages#preview'
  get 'search' => 'notes#search'
  get '/users' => 'pages#index', as: :user_root
  get 'craigslist' => 'pages#craigslist'
  # helloworldrex
  # get ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, Note
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/scrap_result.rb
class ScrapResult < ApplicationRecord
  validates :pid, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ROLES = { 0 => :default, 1 => :admin }

  # attr_reader :role

  # def initialize(email, role_id = 0)
  #   @role = ROLES.has_key?(role_id.to_i) ? ROLES[role_id.to_i] : ROLES[0]
  #   @email = email
  # end

  # def role?(role_title)
  #   self.role == role_title.to_s
  # end

  def admin?
    self.role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to '/notes', notice: exception.message }
      # p exception.message
    end
  end
end

app/controllers/notes_controller.rb
require "#{Rails.root}/lib/assets/note_search"

class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:search, :index]
  load_and_authorize_resource
  skip_authorize_resource :only => [:index, :search]
  include Notes_Mod

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # search Note.all then render
  def search
    # if !user_signed_in?
    #   render body: "<div><h1>Please log in/sign up</h1></div>"
    #   return
    # end

    results = create_serach_result(Note.all)
    notes_array = process_notes_array(results)

    if results.empty?
      render :body => ['nothing in here']
    else
      render file: 'app/views/notes/search.html.erb', layout: false, locals: {:notes => notes_array}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body, :tags)
    end

    def create_serach_result(input)
      search_keys, search_tags = Notes_Mod.create_key_tag(params[:search])
      result_hash = Notes_Mod.give_score(input, search_keys, search_tags)

    # return result in descending order
    # sort by title first then by tags when equal
      result_hash.sort_by { |k, v| [v[0], v[1]] }.reverse
    end

    # generate array of qualifited Notes
    def process_notes_array(array_of_id)
      notes = []
      array_of_id.each do |d|
        notes << Note.find(d[0].to_i)
      end
      notes
    end

    # def check_user_log_in
    #   if !user_signed_in?
    #     render body: "<div><h1>Please log in/sign up</h1></div>"
    #     return
    #   end
    # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include PagesHelper
  include Assets::Scrap_Folder::Scrap_Logic

  # layout 'application', :except => [:preview]
  def index
    # @s = markdown("
    #   ```javascript
    #   var s = 'hello world';
    #   console.log(s);
    #   ```")
    # puts @s
  end

  def preview
    @text = markdown(params[:text])
    puts '888888888888888'
    puts @text
    render :body => @text
  end

  def testpage
    @notes = Note.all
  end

  def craigslist
    @gigs = ScrapResult.where.not(content: nil).order(datetime: :desc)
    @no_content_gigs = ScrapResult.where(content: nil).size
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def tags_format(array)
    return if array.empty?
    result = ""
    array.each do |i|
      result << (i + ",")
    end
    return "{" + remove_trailing_comma(result) + "}"
  end

  def remove_trailing_comma(string)
    if string[-1] == ","
      string = string[0...-1]
    end
    return string
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new()
    markdown = Redcarpet::Markdown.new(renderer, {:fenced_code_blocks=>true})
    return markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteOrganizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  </head>
  <!-- Navbar begin -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/craigslist">Gigs(Canada)</a>
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Craigslist
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Canada Gigs", craigslist_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->

        <!-- <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> -->

      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
      <%= render :partial=> "notes/log_in", layout: false %>
    </div>
  </nav>
  <!-- Navbar ended -->
  <body>
    <div class='container'>
      <div class='row'>
        <div class='col-sm-8'>
          <% if notice %>
            <p class = "alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <div>
            <%= yield %>
          </div>
        </div>
        <div class="col-sm-4 col-centered">
          <!-- sidebar -->
          <div class='sidebar'>
            <h2>Sidebar</h2>
            <div class="btn-group-vertical" role="group" aria-label="Button group with nested dropdown">
              <button type="button" class="btn btn-outline-success">Empty</button>
              <a href="https://github.com/rexmi" class="btn btn-outline-success">My Github</a>
              <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-outline-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </button>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                  <a class="dropdown-item" href="#">Dropdown link</a>
                  <a class="dropdown-item" href="#">Dropdown link</a>
                </div>
              </div>
            </div>
          </div>
          <!-- sidebar end -->
        </div>
      </div>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= javascript_include_tag 'notes_form.js' %>
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, {:size=>"69x7"} %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, value: tags_format(@note.tags) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_log_in.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-8'>
    </div>
    <div class='col-sm-4'>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>
        <br>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <br>
       <!--  <% user_session[:hello] = 'world' %>
        <%= user_session %> -->
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to 'Login', new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<%= javascript_include_tag 'notes_edit.js' %>
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= button_tag 'Preview', id: "preview-button" %>
<br>
<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>
<br>
<div id="paste-area"></div>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td style="max-width:150px; max-height:30px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;"><%= note.body %></td>
        <td><%= note.tags %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) if can? :edit, Note %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } if can? :delete, Note %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path if can? :create, Note %>
<br>
<%= link_to 'Search', '/' %>

app/views/notes/new.html.erb
<%= javascript_include_tag "notes_new.js" %>
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= button_tag 'Preview', id: "preview-button" %>
<br>
<%= link_to 'Back', notes_path %>
<br>
<div id="paste-area"></div>

app/views/notes/search.html.erb
<% notes.each do |note| %>
  <p>
    <strong><%= note.title %></strong>
  </p>

  <p>
    <%= markdown(note.body) %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= note.tags %>
  </p>
  ---------------------------------------
<% end %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@note.body) %>
</p>

<p id='tags_update_field'>
  <strong>Tags:</strong>
  <%= @note.tags %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/pages/craigslist.html.erb
<p>
  No Content Number: <%= @no_content_gigs %>
</p>

<div class="container-fluid">
  <% @gigs.each do |g| %>
    <div>
      <br>
      <table>
        <thead>
          <tr>
            <th>
              <%= g.city %>
            </th>
            <th>
              <%= g.datetime %>
            </th>
            <th class="mom">
              <%= g.pid %>
            </th>
            <th class="dad">
              <%= button_tag "Hide", class: "btn btn-primary hide-btn", id: g.pid %>
            </th>
          </tr>
        </thead>
        <tbody class= <%= g.pid %>>
          <tr>
            <td>
              <strong>Title</strong>
            </td>
            <td colspan=3>
              <%= g.title %>
            </td>
          </tr>
          <tr>
            <td colspan=4>
              <div>
                <%= link_to g.post_url, g.post_url, { target: :_blank, class: g.pid } %>
              </div>
            </td>
          </tr>
          <tr><td><br></td></tr>
          <tr>
            <td colspan=4 class= <%= g.pid %>>
              <div>
                <%= g.content %>
              </div>
            </td>
          </tr>
          <tr class= <%= g.pid %> >
            <td colspan=4>
              <hr class="style1">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<%= text_field :post, :title, id:'search-queue', size: 35, value: 'future search queue' %>
<p>
  <%= link_to 'New Note', new_note_path if can? :create, Note %>
</p>

<p id='paste-area'>
</p>